name: Secure CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Stage
      run: echo "Build successful"

    - name: Test Stage
      run: |
        echo "Checking if index.html exists"
        test -f index.html

    - name: Static Code Analysis (SAST)
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
